language: node_js
node_js: node
os: linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
#    - firefox
before_install:
- wget https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo install chromedriver /usr/local/bin
#- wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
#- tar xzf geckodriver-v0.24.0-linux64.tar.gz
#- sudo install geckodriver /usr/local/bin
env:
- PARALLEL_BUILD=false PARALLEL_E2E=false E2E_LAUNCH_DELAY=5 EXPLICIT_WAIT_TIMEOUT=20000 TEST_TIMEOUT=60000
cache:
  directories:
  - backend/node_modules
  - frontend/node_modules
  - e2e/node_modules
  - build/node_modules
