language: node_js
node_js:
- '18'
- node
os: linux
addons:
  chrome: stable
  firefox: latest
env:
- PARALLEL_BUILD=false PARALLEL_E2E=false E2E_LAUNCH_DELAY=5 EXPLICIT_WAIT_TIMEOUT=20000 TEST_TIMEOUT=60000
cache:
  directories:
  - src/backend/node_modules
  - src/frontend/node_modules
  - src/e2e/node_modules
  - build/node_modules
