language: node_js
node_js: node
os: linux
addons:
  chrome: stable
  firefox: latest
before_install:
- wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo install chromedriver /usr/local/bin
- wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz -O geckodriver-linux64.tar.gz
- tar -xf geckodriver-linux64.tar.gz
- sudo install geckodriver /usr/local/bin
env:
- PARALLEL_BUILD=false PARALLEL_E2E=false E2E_LAUNCH_DELAY=5 EXPLICIT_WAIT_TIMEOUT=20000 TEST_TIMEOUT=60000
cache:
  directories:
  - src/backend/node_modules
  - src/frontend/node_modules
  - src/e2e/node_modules
  - build/node_modules
