version: '3.4'
services:
  refacto:
    build:
      context: ../build
      dockerfile: ../deployment/Dockerfile
    image: refacto/refacto
    environment:
    - PORT=5000
    - TRUST_PROXY
    - PASSWORD_WORK_FACTOR
    - PASSWORD_SECRET_PEPPER
    - TOKEN_SECRET_PASSPHRASE
    - ENCRYPTION_SECRET_KEY
    - DB_URL=mongodb://db:27017/refacto
    - SSO_GOOGLE_CLIENT_ID
    - SSO_GITHUB_CLIENT_ID
    - SSO_GITHUB_CLIENT_SECRET
    - SSO_GITLAB_CLIENT_ID
    - GIPHY_API_KEY
    depends_on:
    - db
    read_only: true
    ports:
    - "5000:5000"
    deploy:
      mode: replicated
      # note: if more than 1 instance is used, the load
      # balancer must be configured to use URL-hash routing
      # (all connections to the same retro's web socket must
      # go to the same instance for live collaboration)
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 1s
    restart: on-failure
    networks:
    - public
    - svc
  db:
    image: mongo:4
    volumes:
    - data:/data/db
    restart: on-failure
    networks:
    - svc

volumes:
  data:
    name: refacto-data

networks:
  public:
  svc:
    internal: true
